name: bootcamp
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - attrs=19.3.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.0
  - ca-certificates=2019.11.28
  - certifi=2019.11.28
  - cloudpickle=1.2.2
  - cycler=0.10.0
  - cytoolz=0.10.1
  - dask-core=2.10.0
  - dbus=1.13.12
  - decorator=4.4.1
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - glib=2.63.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - imageio=2.6.1
  - importlib_metadata=1.5.0
  - inflect=4.0.0
  - intel-openmp=2019.4
  - ipykernel=5.1.4
  - ipython=7.11.1
  - ipython_genutils=0.2.0
  - jaraco.itertools=5.0.0
  - jedi=0.16.0
  - jinja2=2.11.0
  - joblib=0.14.1
  - jpeg=9b
  - json5=0.8.5
  - jsonschema=3.2.0
  - jupyter_client=5.3.4
  - jupyter_core=4.6.1
  - jupyterlab=1.2.6
  - jupyterlab_server=1.0.6
  - kiwisolver=1.1.0
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libsodium=1.0.17
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.9
  - markupsafe=1.1.1
  - matplotlib=3.1.1
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - more-itertools=8.2.0
  - nbconvert=5.6.1
  - nbformat=5.0.4
  - ncurses=6.1
  - networkx=2.4
  - notebook=6.0.3
  - numpy=1.18.1
  - numpy-base=1.18.1
  - olefile=0.46
  - openssl=1.1.1d
  - pandoc=2.9.1.1
  - pandocfilters=1.4.2
  - parso=0.6.0
  - pcre=8.43
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.0.0
  - pip=20.0.2
  - prometheus_client=0.7.1
  - prompt_toolkit=3.0.3
  - ptyprocess=0.6.0
  - pygments=2.5.2
  - pyparsing=2.4.6
  - pyqt=5.9.2
  - pyrsistent=0.15.7
  - python=3.7.6
  - python-dateutil=2.8.1
  - pytz=2019.3
  - pywavelets=1.1.1
  - pyzmq=18.1.1
  - qt=5.9.7
  - readline=7.0
  - scikit-image=0.15.0
  - scikit-learn=0.22.1
  - scipy=1.3.2
  - send2trash=1.5.0
  - setuptools=45.1.0
  - sip=4.19.8
  - six=1.14.0
  - sqlite=3.30.1
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.8
  - toolz=0.10.0
  - tornado=6.0.3
  - traitlets=4.3.3
  - wcwidth=0.1.8
  - webencodings=0.5.1
  - wheel=0.33.6
  - xz=5.2.4
  - zeromq=4.3.2
  - zipp=2.1.0
  - zlib=1.2.11
  - zstd=1.3.7

